
#ifndef IMCLIENT_CMDS_REGS_H_
#define IMCLIENT_CMDS_REGS_H_


// Comandos
#define IM_CLIENT_CMD_GET				0x01
#define IM_CLIENT_CMD_SET				0x02
#define IM_CLIENT_CMD_RESET				0x03
#define IM_CLIENT_CMD_RESP_GET			0x0a
#define IM_CLIENT_CMD_EVENT				0x0b
#define IM_CLIENT_CMD_KEEPALIVE			0x10
#define IM_CLIENT_CMD_ACK				0x11
#define IM_CLIENT_CMD_DISPARAR			0x12
#define IM_CLIENT_CMD_LOGIN				0x13
#define IM_CLIENT_CMD_RESP_LOGIN		0x14

#define IM_CLIENT_CMD_ENVIAR_ZONAS			0x20
#define IM_CLIENT_CMD_ENVIAR_USUARIOS		0x21
#define IM_CLIENT_CMD_ENVIAR_PARTICIONES	0x22
#define IM_CLIENT_CMD_ENVIAR_NODOS			0x23
#define IM_CLIENT_CMD_PEDIR_ZONAS			0x24

#define IM_CLIENT_CMD_SINCRO_FYH		0x26
#define IM_CLIENT_CMD_PEDIR_FYH			0x27
#define IM_CLIENT_CMD_RESP_PEDIR_FYH	0x28

#define IM_CLIENT_CMD_RESET_CLAVES			0x30
#define IM_CLIENT_CMD_RESP_RESET_CLAVES		0x31


// Registros
#define IM_CLIENT_REG_ESTADO					0x0001
#define IM_CLIENT_REG_OPEN_CLOSE				0x0002
#define IM_CLIENT_REG_RED						0x0003
#define IM_CLIENT_REG_BATERIA					0x0004
#define IM_CLIENT_REG_ESTADO_MPXH				0x0005
#define IM_CLIENT_REG_SONANDO_READY				0x0006
#define IM_CLIENT_REG_INCLUSION					0x0007
#define IM_CLIENT_REG_MEMORIA					0x0008
#define IM_CLIENT_REG_ESTADO_ZONAS				0x0009
#define IM_CLIENT_REG_EVENTOS					0x000A
#define IM_CLIENT_REG_REPLAY					0x000B
#define IM_CLIENT_REG_EVENTOS_CUSTOM			0x000C
#define IM_CLIENT_REG_NODOS						0x000D
#define IM_CLIENT_REG_USUARIOS					0x000E
#define IM_CLIENT_REG_ZONAS						0x000F
#define IM_CLIENT_REG_PARTICIONES				0x0010
#define IM_CLIENT_REG_ESTADO_NODOS				0x0011
#define IM_CLIENT_REG_FECHA						0x0012
#define IM_CLIENT_REG_HORA						0x0013
#define IM_CLIENT_REG_FECHA_HORA				0x0014
#define IM_CLIENT_REG_DISPARO					0x0015
#define IM_CLIENT_REG_CONFIGURACION_NODOS		0x0016
#define IM_CLIENT_REG_CONFIGURACION_TIEMPO		0x0017
#define IM_CLIENT_REG_CONFIGURACION_ROBO		0x0018
#define IM_CLIENT_REG_MENSAJE_TCLD				0x0019
#define IM_CLIENT_REG_NOMBRE_COM				0x001A
#define IM_CLIENT_REG_EVENTO_CUSTOM				0x001B
#define IM_CLIENT_REG_MENSAJE_MPXH				0x001C
#define IM_CLIENT_REG_ESTADO_SENSORES			0x001D
#define IM_CLIENT_REG_ESTADO_DISPOSITIVOS		0x001E
#define IM_CLIENT_REG_NOMBRES_AUTOMATIZACIONES	0x001F
#define IM_CLIENT_REG_NODO_TEMPORIZADO			0x0020
#define IM_CLIENT_REG_CONFIGURACION_MONITOREO	0x0021
#define IM_CLIENT_REG_SOCKET_BROKER				0x0050


#endif /* IMCLIENT_CMDS_REGS_H_ */