/**
 * \file
 *
 * \brief User board configuration template
 *
 * Copyright (c) 2013-2018 Microchip Technology Inc. and its subsidiaries.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Subject to your compliance with these terms, you may use Microchip
 * software and any derivatives exclusively with Microchip products.
 * It is your responsibility to comply with third party license terms applicable
 * to your use of third party software (including open source software) that
 * may accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE
 * LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 * LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE
 * SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 * ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY
 * RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * \asf_license_stop
 *
 */
/*
 * Support and FAQ: visit <a href="https://www.microchip.com/support/">Microchip Support</a>
 */

#ifndef CONF_BOARD_H
#define CONF_BOARD_H

#include <compiler.h>

#define BUTTON_0_PIN		PIN_PA17
#define LED_VERDE_PIN		PIN_PA12
#define LED_ROJO_PIN		PIN_PA13
#define MPXH_ENT			PIN_PA15
#define MPXH_SAL			PIN_PA14

#define DUTY_INT			PIN_PA19
#define DUTY_PAL			PIN_PA18

/*
UARTS INVERTIDAS: para que la UART de la consola salga por donde hay pads en el PCB
#define PROBADOR_UART_MODULE              SERCOM2
#define PROBADOR_UART_SERCOM_MUX_SETTING  USART_RX_2_TX_0_XCK_1
#define PROBADOR_UART_SERCOM_PINMUX_PAD0  PINMUX_PA08D_SERCOM2_PAD0
#define PROBADOR_UART_SERCOM_PINMUX_PAD1  PINMUX_UNUSED
#define PROBADOR_UART_SERCOM_PINMUX_PAD2  PINMUX_PA10D_SERCOM2_PAD2
#define PROBADOR_UART_SERCOM_PINMUX_PAD3  PINMUX_UNUSED
#define PROBADOR_UART_SERCOM_DMAC_ID_TX   SERCOM2_DMAC_ID_TX
#define PROBADOR_UART_SERCOM_DMAC_ID_RX   SERCOM2_DMAC_ID_RX

#define EDBG_CONSOLE_MODULE              SERCOM5
#define EDBG_CONSOLE_SERCOM_MUX_SETTING  USART_RX_3_TX_2_XCK_3
#define EDBG_CONSOLE_SERCOM_PINMUX_PAD0  PINMUX_UNUSED
#define EDBG_CONSOLE_SERCOM_PINMUX_PAD1  PINMUX_UNUSED
#define EDBG_CONSOLE_SERCOM_PINMUX_PAD2  PINMUX_PA20C_SERCOM5_PAD2
#define EDBG_CONSOLE_SERCOM_PINMUX_PAD3  PINMUX_PA21C_SERCOM5_PAD3
#define EDBG_CONSOLE_SERCOM_DMAC_ID_TX   SERCOM5_DMAC_ID_TX
#define EDBG_CONSOLE_SERCOM_DMAC_ID_RX   SERCOM5_DMAC_ID_RX
*/


#define PROBADOR_UART_MODULE              SERCOM5
#define PROBADOR_UART_SERCOM_MUX_SETTING  USART_RX_3_TX_2_XCK_3
#define PROBADOR_UART_SERCOM_PINMUX_PAD0  PINMUX_UNUSED
#define PROBADOR_UART_SERCOM_PINMUX_PAD1  PINMUX_UNUSED
#define PROBADOR_UART_SERCOM_PINMUX_PAD2  PINMUX_PA20C_SERCOM5_PAD2
#define PROBADOR_UART_SERCOM_PINMUX_PAD3  PINMUX_PA21C_SERCOM5_PAD3
#define PROBADOR_UART_SERCOM_DMAC_ID_TX   SERCOM5_DMAC_ID_TX
#define PROBADOR_UART_SERCOM_DMAC_ID_RX   SERCOM5_DMAC_ID_RX


#define EDBG_CONSOLE_MODULE              SERCOM1
#define EDBG_CONSOLE_SERCOM_MUX_SETTING  USART_RX_3_TX_2_XCK_3
#define EDBG_CONSOLE_SERCOM_PINMUX_PAD0  PINMUX_UNUSED
#define EDBG_CONSOLE_SERCOM_PINMUX_PAD1  PINMUX_UNUSED
#define EDBG_CONSOLE_SERCOM_PINMUX_PAD2  PINMUX_PA30D_SERCOM1_PAD2
#define EDBG_CONSOLE_SERCOM_PINMUX_PAD3  PINMUX_PA31D_SERCOM1_PAD3
#define EDBG_CONSOLE_SERCOM_DMAC_ID_TX   SERCOM1_DMAC_ID_TX
#define EDBG_CONSOLE_SERCOM_DMAC_ID_RX   SERCOM1_DMAC_ID_RX



#define CONF_MASTER_SPI_MODULE  SERCOM3
#define CONF_MASTER_MUX_SETTING SPI_SIGNAL_MUX_SETTING_E
#define CONF_MASTER_PINMUX_PAD0 PINMUX_PA22C_SERCOM3_PAD0
#define CONF_MASTER_PINMUX_PAD1 PINMUX_UNUSED
#define CONF_MASTER_PINMUX_PAD2 PINMUX_PA24C_SERCOM3_PAD2
#define CONF_MASTER_PINMUX_PAD3 PINMUX_PA25C_SERCOM3_PAD3
#define SPI_25LC1024_SS_PIN     PIN_PA23

#endif // CONF_BOARD_H
