service:
  name: service-iot

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  region: sa-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    MONGODB_CONNECTION_STRING: ${self:custom.MongoDb.connectionString}
    MONGODB_DB_NAME: ${self:custom.MongoDb.dbName}
    IOT_ENDPOINT: ${self:custom.Iot.endpoint}
    SNS_PLATFORM_FCM_ARN: ${self:custom.Sns.arnFcm}
  iamRoleStatements:
    - ${file(iam/IoTConnectPublishIAM.yml):IoTConnectIAM}
    - ${file(iam/IoTConnectPublishIAM.yml):IoTPublishIAM}
    - ${file(iam/PushNotificationsSnsIAM.yml):PushNotificationsSnsIAM}

resources:
  Resources:
    EventEstadoSqsTopicRule: ${file(resources/EventEstadoSqsTopicRule.yml):EventEstadoSqsTopicRule}
    EventEstadoSqsQueuePublishRole: ${file(resources/roles/EventEstadoSqsQueuePublishRole.yml):EventEstadoSqsQueuePublishRole}
    EventEstadoSqsQueue: ${file(resources/EventEstadoSqsQueue.yml):EventEstadoSqsQueue}


functions:
  iotPedirFyH:
    handler: src/handlers/iotPedirFyH.handler
    events:
      - iot:
          sql: "SELECT decode(encode(*, 'base64'), 'base64') AS payload, topic(1) AS clientId, timestamp() AS timestamp FROM '+/event/pedir_fh'"
          sqlVersion: "2016-03-23"

  iotEventEstado:
    handler: src/handlers/iotEventEstado.handler
    events:
      - sqs:
          arn: ${self:custom.eventEstadoSqsQueue.arn}
          batchSize: 5
          maximumBatchingWindow: 1 

  iotEventOpenClose:
    handler: src/handlers/iotEventOpenClose.handler
    events:
      - iot:
          sql: "SELECT decode(encode(*, 'base64'), 'base64') AS payload, topic(1) AS clientId, timestamp() AS timestamp FROM '+/event/open_close'"
          sqlVersion: "2016-03-23"

custom:
  Iot:
    endpoint: a34024whcwieqd.iot.sa-east-1.amazonaws.com
    arn: arn:aws:iot:${self:provider.region}:${aws:accountId}

  MongoDb:
    connectionString: ${ssm:/db/atlas-connection-string~true}
    dbName: com38

  Sns:
    arnFcm: arn:aws:sns:${self:provider.region}:${aws:accountId}:app/GCM/COM38App

  eventEstadoSqsRule:
    name: EventEstadoSqsTopicRule_${self:provider.stage}    #no soporta guión del medio en el nombre
    arn: !GetAtt EventEstadoSqsTopicRule.Arn
  eventEstadoSqsQueue:
    name: EventEstadoSqsQueue-${self:provider.stage}
    arn: !GetAtt EventEstadoSqsQueue.Arn
    url: !Ref EventEstadoSqsQueue
  eventEstadoSqsQueuePublishRole:
    arn: !GetAtt EventEstadoSqsQueuePublishRole.Arn

  bundle:
    linting: false